import React, { createContext, useContext } from "react";
import type { Role } from "@/types";

export interface AppContextType {
  selectedRole: Role | null;
  setSelectedRole: React.Dispatch<React.SetStateAction<Role | null>>;
  isConsentOpen: boolean;
  setIsConsentOpen: React.Dispatch<React.SetStateAction<boolean>>;
  isOrientationDismissed: boolean;
  setIsOrientationDismissed: React.Dispatch<React.SetStateAction<boolean>>;
  showOrientationModal: boolean;
  setShowOrientationModal: React.Dispatch<React.SetStateAction<boolean>>;
  otp: string[];
  setOtp: React.Dispatch<React.SetStateAction<string[]>>;
  showToast: boolean;
  setShowToast: React.Dispatch<React.SetStateAction<boolean>>;
  toastMessage: string;
  setToastMessage: React.Dispatch<React.SetStateAction<string>>;
  registeredEvents: number[];
  setRegisteredEvents: React.Dispatch<React.SetStateAction<number[]>>;
  appliedProjects: number[];
  setAppliedProjects: React.Dispatch<React.SetStateAction<number[]>>;
  likedProjects: number[];
  setLikedProjects: React.Dispatch<React.SetStateAction<number[]>>;
  formStep: number;
  setFormStep: React.Dispatch<React.SetStateAction<number>>;
  formData: any;
  setFormData: React.Dispatch<React.SetStateAction<any>>;
  projectStatus: "matched" | "active" | "completed";
  setProjectStatus: React.Dispatch<React.SetStateAction<"matched" | "active" | "completed">>;
  showPulseCheck: boolean;
  setShowPulseCheck: React.Dispatch<React.SetStateAction<boolean>>;
  pulseCheckSubmitted: boolean;
  setPulseCheckSubmitted: React.Dispatch<React.SetStateAction<boolean>>;
  showFeedbackForm: boolean;
  setShowFeedbackForm: React.Dispatch<React.SetStateAction<boolean>>;
  feedbackSubmitted: boolean;
  setFeedbackSubmitted: React.Dispatch<React.SetStateAction<boolean>>;
  referralCount: number;
  setReferralCount: React.Dispatch<React.SetStateAction<number>>;
  isChatOpen: boolean;
  setIsChatOpen: React.Dispatch<React.SetStateAction<boolean>>;
  isDRActive: boolean;
  setIsDRActive: React.Dispatch<React.SetStateAction<boolean>>;
  drResponses: any[];
  setDrResponses: React.Dispatch<React.SetStateAction<any[]>>;
  hasSubmittedAvailability: boolean;
  setHasSubmittedAvailability: React.Dispatch<React.SetStateAction<boolean>>;
  drDeploymentLog: any[];
  setDrDeploymentLog: React.Dispatch<React.SetStateAction<any[]>>;
  isDRClosed: boolean;
  setIsDRClosed: React.Dispatch<React.SetStateAction<boolean>>;
  chatMessages: any[];
  setChatMessages: React.Dispatch<React.SetStateAction<any[]>>;
  clonedProject: any;
  setClonedProject: React.Dispatch<React.SetStateAction<any>>;
  activeProject: any;
  setActiveProject: React.Dispatch<React.SetStateAction<any>>;
  supportHistory: any[];
  setSupportHistory: React.Dispatch<React.SetStateAction<any[]>>;
  showSupportModal: boolean;
  setShowSupportModal: React.Dispatch<React.SetStateAction<boolean>>;
  supportSubject: string;
  setSupportSubject: React.Dispatch<React.SetStateAction<string>>;
  ngoData: any;
  setNgoData: React.Dispatch<React.SetStateAction<any>>;
  adminActiveTab: string;
  setAdminActiveTab: React.Dispatch<React.SetStateAction<string>>;
  auditLogs: any[];
  setAuditLogs: React.Dispatch<React.SetStateAction<any[]>>;
  addAuditLog: (action: string, details: string) => void;
  triggerToast: (message: string) => void;
  handleRoleSelect: (role: Role) => void;
  handleFormSubmit: (e: React.FormEvent) => void;
  handleConsentAccept: () => void;
  
  handleOtpVerify: () => void;
}

export const AppContext = createContext<AppContextType | null>(null);

export const useAppContext = () => {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error("useAppContext must be used within AppProvider");
  return ctx;
};
